version: "3.0.{build}"

image:
  - macos-monterey
  - Visual Studio 2019
  - Ubuntu2204 # Newer Ubuntu version with GLIBC 2.28 support

platform:
  - x64

environment:
  nodejs_version: 22.12.0

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -match "Visual Studio") {
          choco install nvm
          # Use the direct path to nvm since the PATH might not be refreshed immediately
          $nvmPath = "C:\ProgramData\chocolatey\lib\nvm.install\tools\nvm.exe"
          & $nvmPath install $env:nodejs_version
          & $nvmPath use $env:nodejs_version
      }
  - sh: |
      if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2204" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential
      fi
  - npm install -g yarn
  - yarn

build_script:
  - yarn dist

artifacts:
  - path: dist/*.exe # Windows
  - path: dist/*.dmg # macOS
  - path: dist/*.AppImage # Linux

test: false
