version: "{build}"

# Define build images for each platform
image:
  - Visual Studio 2022
  - macos-monterey
  - Ubuntu2204

platform:
  - x64

environment:
  nodejs_version: "22"

install:
  # Windows setup
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2022") {
        Write-Host "Installing Node.js $env:nodejs_version for Windows"
        Install-Product node $env:nodejs_version
        npm install -g yarn
        npm install -g node-gyp
        npm config set msvs_version 2022
      }

  # macOS setup
  - sh: |
      if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "macos-monterey" ]]; then
        brew install node@22
        npm install -g yarn
        npm install -g node-gyp
      fi

  # Ubuntu setup
  - sh: |
      if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2204" ]]; then
        sudo apt-get update
        sudo apt-get install -y nodejs npm yarn build-essential python3 g++
      fi

  # Common for all platforms
  - yarn install --frozen-lockfile

build_script:
  # Windows build
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2022") {
        Write-Host "Building on Windows..."
        yarn dist
      }

  # Unix builds
  - sh: |
      if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "macos-monterey" || "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2204" ]]; then
        echo "Building on Unix systems..."
        yarn dist
      fi

artifacts:
  - path: dist/*.exe
  - path: dist/*.dmg
  - path: dist/*.AppImage

test: false
