version: "3.0.{build}"

image:
  - Visual Studio 2022
  - macos-monterey
  - Ubuntu2204

platform:
  - x64

environment:
  nodejs_version: "22"

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  # Windows: Install Node.js and Yarn properly
  - ps: |
      Write-Host "Installing Node.js $env:nodejs_version for Windows"
      choco install nodejs --version $env:nodejs_version -y
      npm install -g yarn

  # macOS and Ubuntu: Use package managers directly
  - sh: |
      if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2204" ]]; then
        sudo apt-get update
        sudo apt-get install -y nodejs npm yarn
      elif [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "macos-monterey" ]]; then
        brew install node@22 || true
        npm install -g yarn
      fi

  # Common installation for all platforms
  - ps: |
      Write-Host "Installing project dependencies with Yarn..."
      yarn install --frozen-lockfile
  - sh: yarn install --frozen-lockfile

build_script:
  # Building the project using Yarn on all platforms
  - ps: |
      Write-Host "Building on Windows..."
      yarn dist
  - sh: |
      echo "Building on Unix systems..."
      yarn dist

artifacts:
  - path: dist/*.exe # Windows executable
  - path: dist/*.dmg # macOS disk image
  - path: dist/*.AppImage # Linux AppImage package

test: false
