version: "3.0.{build}"

image:
  - Visual Studio 2019

platform:
  - x64

environment:
  nodejs_version: 22

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: nvm install $nodejs_version
  - npm install -g yarn
  - yarn

build_script:
  - yarn build
  - yarn dist --win
  - cmd: dir dist
  - cmd: dir dist\win-unpacked
  - cmd: dir build
  - cmd: dir public

artifacts:
  - path: dist\*.exe
  - path: dist\win-unpacked\*.exe

test: false