version: "3.0.{build}"

image:
  - Visual Studio 2019
  - macos-monterey
  - Ubuntu2204

platform:
  - x64

environment:
  nodejs_version: 22.12.0

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -match "Visual Studio") {
          choco install nodejs --version=$env:nodejs_version --allow-downgrade -y
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
      }
  - sh: |
      if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2204" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential
      fi
  - npm install -g yarn
  - yarn

build_script:
  - yarn dist

artifacts:
  - path: dist/*.exe # Windows
  - path: dist/*.dmg # macOS
  - path: dist/*.AppImage # Linux

test: false
