version: 3.0.{build}
branches:
  only:
    - master
image:
  - Visual Studio 2022
  - macos-monterey
  - Ubuntu2204
platform: x64
environment:
  nodejs_version: "22"
  npm_config_script_shell: "cmd.exe"
install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: |
      if [ "$env:OS" != "Windows_NT" ]; then
        . $HOME/.nvm/nvm.sh
        nvm install $env:nodejs_version
      fi
  - npm install -g yarn
  - yarn install
build_script:
  - yarn dist
artifacts:
  - path: dist/*.exe
  - path: dist/*.dmg
  - path: dist/*.AppImage
test: false
