version: '2.0.{build}'

image:
  - Visual Studio 2017
  - macos
  - Ubuntu

platform:
  - x64

environment:
  nodejs_version: 14.15.4

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: nvm install $nodejs_version
  - npm install -g yarn
  - yarn

before_build:
  - cmd: xcopy /E /I public\hex dist\public\hex     # Windows
  - sh: cp -R public/hex dist/public/hex             # macOS and Linux

build_script:
  - yarn dist
  
artifacts:
  - path: dist/*.exe                                 # Windows
  - path: dist/*.dmg                                 # macOS
  - path: dist/*.AppImage                            # Linux

test: off
