version: "3.0.{build}"

image:
  - Visual Studio 2022
  - macos-monterey
  - Ubuntu2204

platform:
  - x64

environment:
  nodejs_version: "22"

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # Install project dependencies
  - sh: |
      if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2204" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential
      fi
  - npm install -g yarn
  - yarn

build_script:
  - yarn dist

artifacts:
  - path: dist/*.exe # Windows
  - path: dist/*.dmg # macOS
  - path: dist/*.AppImage # Linux

test: false
