name: Build and Release App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Clean Electron-Builder Cache (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: rm -rf ~/.cache/electron-builder

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build Application
        run: yarn build

      - name: Package Application (Electron Builder)
        run: yarn dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            dist/
            !dist/**/*.map

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Prepare Files for Release
        run: |
          mkdir -p release-assets
          cp dist/*.{exe,dmg,AppImage} release-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: release-assets/*
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: "Automated release from CI pipeline"
          draft: false
          prerelease: false